/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/**
 *
 * @author 
 */
public class Google extends javax.swing.JFrame {
    
    private static final Point point = new Point();
    /**
     * Creates new form Google
     * @param op
     */
    public Google(Operacoes op) {
        setUndecorated(true);
        initComponents();
        setIcon();
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e){
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        
        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e){
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        closeButton.addActionListener(op);
        closeButton1.addActionListener(op);
        googleSearch.addActionListener(op);
        imLucky.addActionListener(op);
        minimizeButton.addActionListener(op);
        search.addActionListener(op);
        
    }
    
    /**Método que altera o ícone da aplicação
     * 
    */
    private void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("chrome_icon.png")));
    }

    public JButton getCloseButton() {
        return closeButton;
    }

    public JButton getCloseButton1() {
        return closeButton1;
    }

    public JButton getGoogleSearch() {
        return googleSearch;
    }

    public JButton getImLucky() {
        return imLucky;
    }

    public JButton getMinimizeButton() {
        return minimizeButton;
    }

    public JTextField getSearch() {
        return search;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        imLucky = new javax.swing.JButton();
        googleSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JButton();
        closeButton1 = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 185, 189)));
        jScrollPane1.setOpaque(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setAutoscrolls(false);
        search.setBorder(null);
        search.setFocusCycleRoot(true);
        search.setFocusTraversalPolicyProvider(true);
        search.setOpaque(false);
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 720, 60));

        imLucky.setBorderPainted(false);
        imLucky.setContentAreaFilled(false);
        jPanel1.add(imLucky, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 170, 40));

        googleSearch.setBorderPainted(false);
        googleSearch.setContentAreaFilled(false);
        jPanel1.add(googleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\victo\\Desktop\\Interface\\google.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 730));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 1000, 680));

        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        getContentPane().add(minimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 30, 30));

        closeButton1.setBorderPainted(false);
        closeButton1.setContentAreaFilled(false);
        getContentPane().add(closeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 20, 20));

        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/googleBar.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 185, 189)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JButton googleSearch;
    private javax.swing.JButton imLucky;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
