/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JButton;
import javax.swing.JScrollPane;

/**
 *
 * @author victo
 */
public class Home extends javax.swing.JFrame {

    private static final Point point = new Point();
    
    /**
     * Creates new form Sites
     */
    public Home(Operacoes op) {
        setUndecorated(true);
        initComponents();
        BBC.addActionListener(op);
        CBS.addActionListener(op);
        CNN.addActionListener(op);
        
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e){
                point.x = e.getX();
                point.y = e.getY();
            }
        });
        
        this.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent e){
                Point p = getLocation();
                setLocation(p.x + e.getX() - point.x, p.y + e.getY() - point.y);
            }
        });
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    }

    public JButton getBBC() {
        return BBC;
    }

    public JButton getCBS() {
        return CBS;
    }

    public JButton getCNN() {
        return CNN;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBS = new javax.swing.JButton();
        CNN = new javax.swing.JButton();
        BBC = new javax.swing.JButton();
        topLabel = new javax.swing.JLabel();
        bottonLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBS.setBorderPainted(false);
        CBS.setContentAreaFilled(false);
        getContentPane().add(CBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 50, 70));

        CNN.setBorderPainted(false);
        CNN.setContentAreaFilled(false);
        getContentPane().add(CNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, 50, 70));

        BBC.setBorderPainted(false);
        BBC.setContentAreaFilled(false);
        getContentPane().add(BBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 690, 50, 70));

        topLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/top_bar.png"))); // NOI18N
        getContentPane().add(topLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bottonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bar+nav.png"))); // NOI18N
        getContentPane().add(bottonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, -1));

        jScrollPane1.setBorder(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\victo\\Desktop\\Interface\\GoogleNews\\App_page.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 533, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBC;
    private javax.swing.JButton CBS;
    private javax.swing.JButton CNN;
    private javax.swing.JLabel bottonLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
